### ISSUE TITLE
Compatibilidade Magento 1.7

### ISSUE THREAD

**Issue by antoniokarlos** [techspotbr/Techspot_Brcustomer#2]
Ola boa noite!

Gostaria de saber se ssse módulo funciona no magento 1.7. Se sim, se é possível eu fazer um radiobutton para saber se a pessoa que está se cadastrando quer se cadastrar como Pf ou PJ.

Agradeço desde já!

**Comment by techspotbr** [comment]
Desculpe a demora em responder. Infelizmente esse módulo compatível apenas com magento 2
